### PR TITLE
updated the code to use es5 class inheritance

### PR DESCRIPTION
**Pull request by ahdinosaur**
hey @jed, i appreciate your module here. :smile: 

the impetus for this change: i tried using this with babel and ES6 classes as intended, but ran into problems where classes **require** you to instantiate them with `new`, but [levelup doesn't use `new` to instantiate the leveldown](https://github.com/Level/levelup/blob/6e78bff8e8f6cbaad97023606a67e2befdff7fc9/lib/levelup.js#L114-L115).

what i did:
- updated the code to use `inherits` and `assign` to do inheritance in a more common style
- ~~replaced the ES6 code with ES5 equivalents~~
- ~~made the code comply with [standard style](http://standardjs.com/)~~

i'm curious how you feel about this change and whether this pull request has potential to be merged in. thanks! :watermelon:

### CODE REVIEW

**Comment by jed** [comment]
thanks, @ahdinosaur. to be honest, i think the core issue could be solved by exposing not a the compiled constructor, but a function that runs the constructor itself. the rest of it is style opinions that i don't feel strongly about, and would like to consider in a separate PR if you're cool with that.

**Comment by ahdinosaur** [comment]
> to be honest, i think the core issue could be solved by exposing not a the compiled constructor, but a function that runs the constructor itself.

yeah, that makes sense, a `AbstractStreamLevelDOWN.create` would indeed solve that specific issue.

>  the rest of it is style opinions that i don't feel strongly about, and would like to consider in a separate PR if you're cool with that.

so is https://github.com/holodex/abstract-stream-leveldown/commit/05305b09f893b002db97b143b9577a528a946161 friendly and i should remove https://github.com/holodex/abstract-stream-leveldown/commit/530cd7851ef1be51bbf9a7e72f47b86822acde94 from this PR, or are there specific styles changes i should remove?

**Comment by jed** [comment]
yeah, i'd say tease them out and we can take it from there.

**Comment by ahdinosaur** [comment]
is the es6 -> es5 a style opinion?

**Comment by jed** [comment]
it is, but since it's so lightly used here i don't feel too strongly about it. i've added you as a collaborator, so feel free to make the changes you'd like. would still like to see these PR'ed separately though.

**Comment by ahdinosaur** [comment]
@jed thanks for the invite. :cat: please take another look (PTAL) if this PR is reasonable.

**Comment by jed** [comment]
i've added you on npm as well, so go for it.

**Comment by ahdinosaur** [comment]
sweet, [tagged](https://github.com/jed/abstract-stream-leveldown/releases/tag/1.1.1) and [published](https://www.npmjs.com/package/abstract-stream-leveldown).

**Pull request merged**
